### ISSUE TITLE
Problem about the released checkpoint

### ISSUE THREAD

**Issue by RERV** [salesforce/ALBEF#12]
Hi, Thanks for your excellent work!
    I want to ask which datasets are the released checkpoints pretrained on, 4m dataset or 4 + 10m dataset? Since there are two pretrained dataset in your paper.

Thanks!

**Comment by LiJunnan1992** [comment]
Hi, the checkpoints are pretrained on 14M dataset. Thanks!

**Comment by RERV** [comment]
Thanks!
