### ISSUE TITLE
Key Error When reshaping position embedding.

### ISSUE THREAD

**Issue by jipson7** [salesforce/ALBEF#14]
Hi there, I am trying to evaluate the pretrained coco model you provided. Originally I got the same error as the original poster in #7 . However, setting distill to `False` does not fix the issue for me. It seems as though the checkpoint is already the model, therefore the line in #7 can be changed from `state_dict = checkpoint['model']` to `state_dict = checkpoint`. However when I do this it gives me another key error here on line 190: 

```
m_pos_embed_reshaped = interpolate_pos_embed(state_dict['visual_encoder_m.pos_embed'],model.visual_encoder_m) 

```

Inidicating that the key `'visual_encoder_m.pos_embed'` does not exist. Is this an error with the code, checkpoint, or am I doing something wrong? For what its worth the key `visual_encoder.pos_embed` does exist. Any guidance is appreciated.

Also, great work.

**Comment by LiJunnan1992** [comment]
Hi, the coco (fine-tuned) checkpoint does not need to reshape the positional embedding, nor does it have visual_encoder_m. The checkpoint loading script in Retrieval.py is intended to load from a pre-trained model. You can remove the reshape code if you want to load from a fine-tuned checkpoint.

Thanks!

**Comment by CQUTWangHong** [comment]
@jipson7 same as me, have you solved the problem?

thank you!

**Comment by Ngheissari** [comment]
> Hi, the coco (fine-tuned) checkpoint does not need to reshape the positional embedding, nor does it have visual_encoder_m. The checkpoint loading script in Retrieval.py is intended to load from a pre-trained model. You can remove the reshape code if you want to load from a fine-tuned checkpoint.
> 
> Thanks!

Hi, trying to finetun on refcoco using grounding from pre trained checkpoint (ALBEF.pth ) as a sanity check and it complains about :
m_pos_embed_reshaped = interpolate_pos_embed(state_dict['visual_encoder_m.pos_embed'],model.visual_encoder_m)   

saying object ALBEF has no visual_encoder_m. If I replace model.visual_encoder_m with visual_encoder it works. So is it a problem with the code or checkpoint ? 

Thank you for your work.
