### ISSUE TITLE
questions about Grounding evaluation

### ISSUE THREAD

**Issue by yechenzhi** [salesforce/ALBEF#15]
In your grounding task, you used 'dets.json' to evaluate your results, how do you get the 'dets.json' file? which object detector did you use?

**Comment by LiJunnan1992** [comment]
Hi, following previous work such as UNITER, we use the object proposal from Mask-RCNN, provided by "Mattnet: Modular attention network for referring expression comprehension."

**Comment by yechenzhi** [comment]
Thank you, your work is amazing, It inspires me a lot, I really appreciate it.
