### ISSUE TITLE
Would you release the pretrained checkpoint on 4M dataset?

### ISSUE THREAD

**Issue by byougert** [salesforce/ALBEF#16]
Hi, thanks for your sharing ALBEF.
I have got that the checkpoint released on Github is pretrained on 14M dataset at [issue12](https://github.com/salesforce/ALBEF/issues/12). I wonder if you would release the pretrained checkpoint on 4M dataset? 

Thanks! ^_^

**Comment by LiJunnan1992** [comment]
Hi, you can find the 4M model here: https://storage.googleapis.com/sfr-pcl-data-research/ALBEF/ALBEF_4M.pth

**Comment by byougert** [comment]
Wow, many THANKS!
