### ISSUE TITLE
Some results issue

### ISSUE THREAD

**Issue by viyjy** [salesforce/ALBEF#19]
Hi Junnan, I have the following questions about the result. Hope that you can help to clarify them, thanks.
1. VQA:
I get the `result` folder after fine-tuning on VQA dataset. Which json file should I use to get test-dev and test-std?
![image](https://user-images.githubusercontent.com/20442927/138797664-b71ebe6e-6684-4f75-a837-745dcea698eb.png)

2. SNLI-VE:
This is the log file after fine-tuning on SNLI-VE dataset. You didn't update the best-epoch, so it is always 0. Should I pick the row which has the best val accuracy as the final result?
![image](https://user-images.githubusercontent.com/20442927/138798113-4bdb9e7d-3d29-4244-9b44-fee7e77a5fbc.png)

3. Grouding
This is the log file after fine-tuning on Ref-COCO. Should I pick the row which has the best val_d as the final result?
![image](https://user-images.githubusercontent.com/20442927/138798773-8f316d16-cc3a-40d5-9f6e-52d70929f7ba.png)

4. NLVR2
This is the log file after fine-tuning on NLVR2, but I did't find `dev` and `test-P` as shown in your paper, any idea?
![image](https://user-images.githubusercontent.com/20442927/138797444-ef11a6cb-2e02-4108-8d0c-985aed8a3a41.png)

**Comment by haoshuai714** [comment]
Hello! Can NLVR2 datasets be shared?

**Comment by haoshuai714** [comment]
> Thanks very much!

NLVR2

**Comment by viyjy** [comment]
You can find it here: https://github.com/lil-lab/nlvr/tree/master/nlvr2

**Comment by haoshuai714** [comment]
Could you give me a SNLI-VE dataset download link?
