### ISSUE TITLE
pretraining datasets json files

### ISSUE THREAD

**Issue by jayleicn** [salesforce/ALBEF#2]
Hi @LiJunnan1992,

Congrats on your great work, and thanks for releasing the code!! To help reproduce the pretraining experiments, could you release the dataset json files for the pretraining datasets as well? Thanks!

Best,
Jie

**Comment by LiJunnan1992** [comment]
Hi,

Here are the dataset json files (I've also updated the readme). https://storage.googleapis.com/sfr-pcl-data-research/ALBEF/json_pretrain.zip 
For each json file, you need to change the image paths to adapt to your own directory.

Thanks!

**Comment by jayleicn** [comment]
Thanks! This is very helpful. A related question here, I noticed the released VG captions only contain 769K captions (also see Table 8 in this work, screenshot 1 below), while UNITER has 5M VG captions (see Table 1 in UNITER, screenshot 2 below). Is there any sort of filtering used in obtaining the 769K captions from the 5M captions? Could you elaborate this process?


![image](https://user-images.githubusercontent.com/15768405/127068668-dc6d6bb3-ee80-4d91-ab40-f5b5e763c907.png)
![image](https://user-images.githubusercontent.com/15768405/127068811-516ae613-fdfd-4b11-84dd-f95c2c60cb38.png)

**Comment by LiJunnan1992** [comment]
Yes there are 4 filters for VG:
1. remove samples that occur in the evaluation set of COCO or RefCOCO+ 
2 remove duplicate sentences for each image
3. remove sentences whose corresponding region has an area size that is <20% of the image's area size
4. remove sentences that have fewer than 4 words

**Comment by jayleicn** [comment]
Thanks for the prompt reply, I am closing this issue.

**Comment by jayleicn** [comment]
> Yes there are 4 filters for VG:
> 
> 1. remove samples that occur in the evaluation set of COCO or RefCOCO+
> 2. remove duplicate sentences for each image
> 3. remove sentences whose corresponding region has an area size that is <20% of the image's area size
> 4. remove sentences that have fewer than 4 words

Hi @LiJunnan1992, I have some follow-up questions on filters 3 and 4:
(1) Do you have some intuitions on using them?
(2) Did you conduct experiments comparing the difference when using them? 

Thanks!

**Comment by LiJunnan1992** [comment]
Because we perform random image crop during training, filter (3) will decrease the chance that the text does not describe the image. Filter (4) aims to remove less informative text.

Our experiments do not show any significant difference, so we keep them removed because it decreases training time.

**Comment by jayleicn** [comment]
This makes sense. Thanks!
