### ISSUE TITLE
Questions about  Fine-tuned Model Files

### ISSUE THREAD

**Issue by cdqncn** [salesforce/ALBEF#21]
The fine-tuned checkpoint mscoco.pth provided by https://storage.googleapis.com/sfr-pcl-data-research/ALBEF/mscoco.pth (Finetuned checkpoint for retrieval on MSCOCO) is 800MB, but I get 1.69GB checkpoint model after running the Retrieval.py? Could you tell me why?

**Comment by LiJunnan1992** [comment]
Hi, the 1.69GB checkpoint saves the momentum model and the queue, which I have manually removed from the 800MB checkpoint.

**Comment by cdqncn** [comment]
Thanks a lot for your comment!
