### ISSUE TITLE
Some difference between the paper and code

### ISSUE THREAD

**Issue by cdqncn** [salesforce/ALBEF#22]
In the page 3 of the paper, p_m^{i2t} = exp(...)/sum_{i=1}^M(...). I found it is different in code, which is sum_{i=1}^{M+batchsize}, so I think there is a mistake in this detail in the paper.
![image](https://user-images.githubusercontent.com/47705034/140004403-c9daf4e1-0494-4047-96b9-c7eee8ccecbd.png)

![image](https://user-images.githubusercontent.com/47705034/140004439-4d8a2f9d-a688-4d86-b7cd-3de9737e9c74.png)

**Comment by LiJunnan1992** [comment]
Yes you are right, thanks!

**Comment by SKBL5694** [comment]
@cdqncn Hello, I'm fairly new to this code. I found you write some comment for the code. If it is convenient, can you share the comment with me?  I appreciate the help. Thank you
