### ISSUE TITLE
how to test the model？

### ISSUE THREAD

**Issue by CQUTWangHong** [salesforce/ALBEF#23]
hi, I just  want to test the effect of the model.
here is my test code:

`python Retrieval.py  --config ./configs/Retrieval_flickr.yaml --output_dir output/Retrieval_flickr  --checkpoint  model_file/ALBEF.pth --evaluate True`

I have changed the relevant configuration files.

Am I right to test like this？

thx!

**Comment by CQUTWangHong** [comment]
I already  know how to test .
`python   -m torch.distributed.launch --nproc_per_node=4 --use_env Retrieval.py --config ./configs/Retrieval_flickr.yaml --output_dir output/Retrieval_flickr --checkpoint flick30k/model_file/ALBEF.pth --evaluate`

but I get the following error:

Start training
Computing features for evaluation...
```
Traceback (most recent call last):
  File "Retrieval.py", line 379, in <module>
    main(args, config)
  File "Retrieval.py", line 305, in main
    score_val_i2t, score_val_t2i, = evaluation(model_without_ddp, val_loader, tokenizer, device, config)
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "Retrieval.py", line 103, in evaluation
    for image, img_id in data_loader: 
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/ly/.conda/envs/ALBEF/lib/python3.8/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```


my server  memory condition:
                  total        used        free      shared  buff/cache   available
Mem:            62G         33G         28G         11M        753M         28G

How much memory is needed to run this program？

look forward to your reply,thank you.

**Comment by LiJunnan1992** [comment]
Hi, you may want to reduce batch_size_test in the config file and see if the error goes away.

**Comment by CQUTWangHong** [comment]
thank you，

When I only use a GPU to test the model, it reports such an error:
`CUDA out of memory`

when I use 4 gpu distributed parallel, it reports that error:
`OSError: [Errno 12] Cannot allocate memory`

very strange

**Comment by CQUTWangHong** [comment]
hello, @LiJunnan1992 

I test the model on flickr30k  dataset, the output of the model is as follows:

> {"val_txt_r1": 90.23668639053254, "val_txt_r5": 98.0276134122288, "val_txt_r10": 99.11242603550296, "val_txt_r_mean": 95.7922419460881, "val_img_r1": 75.77909270216962, "val_img_r5": 92.48520710059172, "val_img_r10": 95.75936883629191, "val_img_r_mean": 88.00788954635108, "val_r_mean": 91.90006574621958, "test_txt_r1": 88.5, "test_txt_r5": 98.5, "test_txt_r10": 99.2, "test_txt_r_mean": 95.39999999999999, "test_img_r1": 75.92, "test_img_r5": 93.34, "test_img_r10": 96.66, "test_img_r_mean": 88.63999999999999, "test_r_mean": 92.01999999999998, "epoch": 0}

compare with paper's result:
![ALBEF_result](https://cdn.jsdelivr.net/gh/CQUTWangHong/picture/picgo/20211105113136.png)

The effect of the test seems to be a little low.

**Comment by CQUTWangHong** [comment]
By the way, how to use the finetuned checkpoint for retrieval on flickr30k?

**Comment by LiJunnan1992** [comment]
What command do you use to evaluate the checkpoint? You should be able to get the same numbers in the paper.

**Comment by CQUTWangHong** [comment]
Thank you for your patience！
the command:
`python -m torch.distributed.launch --nproc_per_node=4 --use_env Retrieval.py --config ./configs/Retrieval_flickr.yaml --output_dir output/Retrieval_flickr --checkpoint model_file/ALBEF.pth --evaluate`

**Comment by CQUTWangHong** [comment]
one more question

when I use the finetuned checkpoint for retrieval on flickr30k to evaluate:

`python -m torch.distributed.launch --nproc_per_node=4 --use_env Retrieval.py --config ./configs/Retrieval_flickr.yaml --output_dir output/Retrieval_flickr --checkpoint model_file/flickr30k.pth --evaluate`

an error occurred with keyerror：

```
Traceback (most recent call last):
  File "Retrieval.py", line 379, in <module>
    main(args, config)
  File "Retrieval.py", line 261, in main
    state_dict = checkpoint['model']
KeyError: 'model'
```


According to the #7 issue, set distill=False in the config, but it still reports same error.

thank you！

**Comment by CQUTWangHong** [comment]
hi,junnan
I know why reported  KeyError: 'model'
I printed the type of checkpoint and its keys
It doesn't have the key of ’model‘：

`print(checkpoint)`

`odict_keys(['temp', 'visual_encoder.cls_token', 'visual_encoder.pos_embed', 'visual_encoder.patch_embed.proj.weight', 'visual_encoder.patch_embed.proj.bias', 'visual_encoder.blocks.0.norm1.weight', 'visual_encoder.blocks.0.norm1.bias', 'visual_encoder.blocks.0.attn.qkv.weight', 'visual_encoder.blocks.0.attn.qkv.bias', 'visual_encoder.blocks.0.attn.proj.weight', 'visual_encoder.blocks.0.attn.proj.bias', 'visual_encoder.blocks.0.norm2.weight', 'visual_encoder.blocks.0.norm2.bias', 'visual_encoder.blocks.0.mlp.fc1.weight', 'visual_encoder.blocks.0.mlp.fc1.bias', 'visual_encoder.blocks.0.mlp.fc2.weight', 'visual_encoder.blocks.0.mlp.fc2.bias', 'visual_encoder.blocks.1.norm1.weight', 'visual_encoder.blocks.1.norm1.bias', 'visual_encoder.blocks.1.attn.qkv.weight', 'visual_encoder.blocks.1.attn.qkv.bias', 'visual_encoder.blocks.1.attn.proj.weight', 'visual_encoder.blocks.1.attn.proj.bias', 'visual_encoder.blocks.1.norm2.weight', 'visual_encoder.blocks.1.norm2.bias', 'visual_encoder.blocks.1.mlp.fc1.weight', 'visual_encoder.blocks.1.mlp.fc1.bias', 'visual_encoder.blocks.1.mlp.fc2.weight', 'visual_encoder.blocks.1.mlp.fc2.bias', 'visual_encoder.blocks.2.norm1.weight', 'visual_encoder.blocks.2.norm1.bias', 'visual_encoder.blocks.2.attn.qkv.weight', 'visual_encoder.blocks.2.attn.qkv.bias',....`

may be you saved is state_dict, so what you provide the finetuned checkpoint for retrieval on flickr30k can  be directly used as state_dict.

thx!

**Comment by CQUTWangHong** [comment]
oh, junnan,
according to the #14 issue, I know how to solve the keyerror problem.

and the  effect of test:
`{'txt_r1': 95.9, 'txt_r5': 99.8, 'txt_r10': 100.0, 'txt_r_mean': 98.56666666666666, 'img_r1': 85.52, 'img_r5': 97.52, 'img_r10': 98.92, 'img_r_mean': 93.98666666666666, 'r_mean': 96.27666666666667}`

same as the paper.

I really appreciate you!

**Comment by idejie** [comment]
> Thank you for your patience！ the command: `python -m torch.distributed.launch --nproc_per_node=4 --use_env Retrieval.py --config ./configs/Retrieval_flickr.yaml --output_dir output/Retrieval_flickr --checkpoint model_file/ALBEF.pth --evaluate`

Hi @CQUTWangHong ,  

Did you get the same results(Zero-Shot on Flickr30k) as the paper by this command?

I also tested the model on flickr30k dataset, and got the same result as that you  have reported:
```
# val
{'txt_r1': 90.23668639053254, 'txt_r5': 98.0276134122288, 'txt_r10': 99.11242603550296, 'txt_r_mean': 95.7922419460881, 'img_r1': 75.75936883629191, 'img_r5': 92.50493096646943, 'img_r10': 95.75936883629191, 'img_r_mean': 88.00788954635108, 'r_mean': 91.90006574621958}
# test
{'txt_r1': 88.5, 'txt_r5': 98.5, 'txt_r10': 99.2, 'txt_r_mean': 95.39999999999999, 'img_r1': 75.92, 'img_r5': 93.34, 'img_r10': 96.66, 'img_r_mean': 88.63999999999999, 'r_mean': 92.01999999999998}
```

**Comment by CQUTWangHong** [comment]
@idejie 
hh, are you chinese? I will speak Chinese
你用这个Finetuned checkpoint for retrieval on Flickr30k就和paper的结果一致了。

**Comment by idejie** [comment]
@CQUTWangHong 
Thanks a lot!
我是中国人，谢谢你！我这Finetune的结果没问题，Zeroshot是我用的checkpoint不对，应该用在coco上finetune过的。

另外，方便加wechat交流不？我的：fineDJ

**Comment by BUAADreamer** [comment]
> one more question
> 
> when I use the finetuned checkpoint for retrieval on flickr30k to evaluate:
> 
> `python -m torch.distributed.launch --nproc_per_node=4 --use_env Retrieval.py --config ./configs/Retrieval_flickr.yaml --output_dir output/Retrieval_flickr --checkpoint model_file/flickr30k.pth --evaluate`
> 
> an error occurred with keyerror：
> 
> ```
> Traceback (most recent call last):
>   File "Retrieval.py", line 379, in <module>
>     main(args, config)
>   File "Retrieval.py", line 261, in main
>     state_dict = checkpoint['model']
> KeyError: 'model'
> ```
> 
> According to the #7 issue, set distill=False in the config, but it still reports same error.
> 
> thank you！

Did you solve this problem? I got same problem, I set distill=False but can't work.

**Comment by rhyhck** [comment]
> thank you，
> 
> When I only use a GPU to test the model, it reports such an error: `CUDA out of memory`
> 
> when I use 4 gpu distributed parallel, it reports that error: `OSError: [Errno 12] Cannot allocate memory`
> 
> very strange

Hi, I meet this question about "torch.cuda.OutOfMemoryError", how did you solve it?
