### ISSUE TITLE
About memory allocation

### ISSUE THREAD

**Issue by tingxueronghua** [salesforce/ALBEF#24]
I want to do the VQA finetuning. I do not have A100 GPUs, and I could only run on 4 2080Ti GPUs with 11019MB memory. I tried to reduce the batch size to 1 but still got "CUDA out of memory". I want to inquire whether it is normal?

**Comment by aurooj** [comment]
@tingxueronghua Were you able to resolve the problem? I am able to start finetuning on my local gpu but on any other machine I get the same CUDA out of memory error which is not the correct behavior.

**Comment by tingxueronghua** [comment]
maybe you made the same mistake with me? In distributeddataparallel, the batchsize means that per GPU. So when i set batchsize to 4, it means 16 totally. and i can run the code when i set batchsize to 2.

**Comment by aurooj** [comment]
Thanks for your quick reply!
I am running it with batchsize 1 yet getting this error even with single gpu. :/
