### ISSUE TITLE
The ability of Pretrained model for downstream tasks use directly

### ISSUE THREAD

**Issue by EthanGreen75** [salesforce/ALBEF#25]
Thanks for the great work for vision-language multi-modal pretraining.
     Have tried the finetuned model to test flickr30k retrieval task and the statistics is good. 
     My question is that the pretrained model has the aliblity to directly apply on downstream tasks or not ?  When used with the pretrained model ALBEF.pth for flickr30k retrieval task, the recall results are quite not satisfactory. It's a common status for all downstream tasks when use pretrained model or a special case in retrieval task?
      Hope get suggestions.

**Comment by LiJunnan1992** [comment]
Hi, the pre-trained model has been trained on resolution of 256, so you might want to use 256 instead of 384 resolution when directly using the pre-trained model.
Thanks!

**Comment by EthanGreen75** [comment]
> 

it works, thanks very much
