### ISSUE TITLE
Problem in pretraining with SBU

### ISSUE THREAD

**Issue by pqviet** [salesforce/ALBEF#27]
For the SBU dataset (http://www.cs.virginia.edu/~vicente/sbucaptions/), a quite portion of the urls are unaccessible now (many downloaded images have 0 size). How did you deal with this case in pretraining?

**Comment by LiJunnan1992** [comment]
Hi, I only used the images that I could successfully downloaded.

**Comment by pqviet** [comment]
Could you share your download script?
I used torchvision.datasets.sbu, but could download only 28000 images.

**Comment by LiJunnan1992** [comment]
I also used the code of torchvision.datasets.sbu to download.

**Comment by Hritikbansal** [comment]
Any idea as to how to get sbu captions dataset online? https://www.cs.virginia.edu/~vicente/sbucaptions/ seems to throw 403 for me.
