### ISSUE TITLE
Why step_size is set to be 100?

### ISSUE THREAD

**Issue by shizhediao** [salesforce/ALBEF#28]
Hi thanks for your great work.
I have a minor question about your code. 
I saw that the `step_size` is set to 100, and the `warmup_iterations` is `step_size * warmup_epochs`.
May I ask the justification?

Thanks!

**Comment by LiJunnan1992** [comment]
Hi, we warm up for some iterations at the start of pre-training to make training more stable. The warmup_iterations can be adjusted to other values without much effect on the final model's performance.

**Comment by shizhediao** [comment]
ok, thanks.
