### ISSUE TITLE
Problems about the test results

### ISSUE THREAD

**Issue by idejie** [salesforce/ALBEF#29]
Hi, @LiJunnan1992

Thanks for your work and release!

However, I got a lower zero-shot performance on flickr30k, which seems to  be the same as the performance reported in #23 , 
```
# val set
{'txt_r1': 90.23668639053254, 'txt_r5': 98.0276134122288, 'txt_r10': 99.11242603550296, 'txt_r_mean': 95.7922419460881, 'img_r1': 75.75936883629191, 'img_r5': 92.50493096646943, 'img_r10': 95.75936883629191, 'img_r_mean': 88.00788954635108, 'r_mean': 91.90006574621958}
# test set
{'txt_r1': 88.5, 'txt_r5': 98.5, 'txt_r10': 99.2, 'txt_r_mean': 95.39999999999999, 'img_r1': 75.92, 'img_r5': 93.34, 'img_r10': 96.66, 'img_r_mean': 88.63999999999999, 'r_mean': 92.01999999999998}
```

![image](https://user-images.githubusercontent.com/12479824/144558147-0f3070ea-59d5-4ffb-926e-4a6e4e46cb9a.png)

and used this command:
```
python -m torch.distributed.launch --nproc_per_node=8 --use_env Retrieval.py \
--config ./configs/Retrieval_flickr.yaml \
--output_dir output/Retrieval_flickr \
--checkpoint sources/ALBEF.pth --evaluate
```

**Comment by LiJunnan1992** [comment]
Hi! The zero-shot result on flickr is evaluated using the model finetuned on COCO. The ALBEF.pth uses a smaller resolution.

**Comment by idejie** [comment]
@LiJunnan1992 Thanks a lot！ I got the same results as the paper!
