### ISSUE TITLE
the number of training images in pretrained checkpoints

### ISSUE THREAD

**Issue by wqtwjt1996** [salesforce/ALBEF#3]
Can you tell me for your provided "pretrained checkpoints", how many training images did you use, 4M or 14M?

I tested your "pretrained checkpoints" on flickr30k, I got this results with 8 V100 GPUs (32GB):
{'txt_r1': 88.5, 'txt_r5': 98.5, 'txt_r10': 99.2, 'txt_r_mean': 95.39999999999999, 'img_r1': 75.92, 'img_r5': 93.34, 'img_r10': 96.66, 'img_r_mean': 88.63999999999999, 'r_mean': 92.01999999999998}

which is slightly different of your provided results in Table 3 of arxiv paper, especially for TR @1.

**Comment by wqtwjt1996** [comment]
My envs are as follows:
numpy                     1.20.3           py38hf144106_0  
opencv-python             4.5.3.56                 pypi_0    pypi
python                    3.8.10          h49503c6_1_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.9.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
timm                      0.4.12             pyhd8ed1ab_0    conda-forge
torchaudio                0.9.0                      py38    pytorch
torchvision               0.10.0               py38_cu102    pytorch
transformers              4.9.1              pyhd8ed1ab_0    conda-forge

**Comment by LiJunnan1992** [comment]
Hi, the pretrained checkpoint uses 14M images.

As mentioned in our paper, "For zero-shot retrieval on Flickr30K, we evaluate with the model fine-tuned on COCO". Therefore, you can use the COCO checkpoint to reproduce the result in Table 3.

Thanks!

**Comment by wqtwjt1996** [comment]
> Hi, the pretrained checkpoint uses 14M images.
> 
> As mentioned in our paper, "For zero-shot retrieval on Flickr30K, we evaluate with the model fine-tuned on COCO". Therefore, you can use the COCO checkpoint to reproduce the result in Table 3.
> 
> Thanks!

Got it, thanks!
