### ISSUE TITLE
how to split train, val and test dataset of "flickr30k"?

### ISSUE THREAD

**Issue by shoutOutYangJie** [salesforce/ALBEF#30]
I know there is no official split config. what criterion do you apply when you split the dataset.

**Comment by LiJunnan1992** [comment]
Hi, I used the Karpathy split.

**Comment by shoutOutYangJie** [comment]
where can I refer to it?





------------------ Original ------------------
From: Junnan Li ***@***.***&gt;
Date: Tue,Dec 7,2021 8:48 AM
To: salesforce/ALBEF ***@***.***&gt;
Cc: shoutOutYangJie ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [salesforce/ALBEF] how to split train, val and test dataset of"flickr30k"? (Issue #30)





 
Hi, I used the Karpathy split.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiJunnan1992** [comment]
https://cs.stanford.edu/people/karpathy/deepimagesent/
