### ISSUE TITLE
what size of your A100 gpu's memory?

### ISSUE THREAD

**Issue by shoutOutYangJie** [salesforce/ALBEF#31]
80GB or 40GB.?
For accelerating data reading, which method do you apply? 
Thank you

**Comment by LiJunnan1992** [comment]
Hi, I used the 40GB gpu.
Data reading was not a major speed bottleneck, but you could try to resize the image on hard drive because some images could have a high resolution.

**Comment by shoutOutYangJie** [comment]
how about cost time of &nbsp;pretrain stage ?





------------------ Original ------------------
From: Junnan Li ***@***.***&gt;
Date: Wed,Dec 8,2021 5:45 PM
To: salesforce/ALBEF ***@***.***&gt;
Cc: shoutOutYangJie ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [salesforce/ALBEF] what size of your A100 gpu's memory? (Issue#31)





 
Hi, I used the 40GB gpu.
 Data reading was not a major speed bottleneck, but you could try to resize the image on hard drive because some images could have a high resolution.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiJunnan1992** [comment]
Using 8 A100 GPUs, it takes 2-3 days with 4M images, and around 7-8 days with 14M images. You could make training faster by reducing the image resolution to 224 and increasing the batch size, the performance would be roughly the same. You can also try some other memory reduction techniques such as zero-redundancy optimizer.

**Comment by shoutOutYangJie** [comment]
can i use 8 32gb-v100 &nbsp;gpus to reproduce your training result?&nbsp;
by the way, the code of data preprocessing (filter some pairs) will be released?





------------------ Original ------------------
From: Junnan Li ***@***.***&gt;
Date: Wed,Dec 8,2021 6:05 PM
To: salesforce/ALBEF ***@***.***&gt;
Cc: shoutOutYangJie ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [salesforce/ALBEF] what size of your A100 gpu's memory? (Issue#31)





 
Using 8 A100 GPUs, it takes 2-3 days with 4M images, and around 7-8 days with 14M images. You could make training faster by reducing the image resolution to 224 and increasing the batch size, the performance would be roughly the same. You can also try some other memory reduction techniques such as zero-redundancy optimizer.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiJunnan1992** [comment]
Yes I think you could.
The pre-training dataset annotation (image paths and text) is released.

**Comment by sunanhe** [comment]
Hi, do you get similar performance using 8 V100 GPUs?

> can i use 8 32gb-v100 &nbsp;gpus to reproduce your training result?&nbsp; by the way, the code of data preprocessing (filter some pairs) will be released?
> […](#)
> ------------------ Original ------------------ From: Junnan Li ***@***.***&gt; Date: Wed,Dec 8,2021 6:05 PM To: salesforce/ALBEF ***@***.***&gt; Cc: shoutOutYangJie ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [salesforce/ALBEF] what size of your A100 gpu's memory? (Issue#31) Using 8 A100 GPUs, it takes 2-3 days with 4M images, and around 7-8 days with 14M images. You could make training faster by reducing the image resolution to 224 and increasing the batch size, the performance would be roughly the same. You can also try some other memory reduction techniques such as zero-redundancy optimizer. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangbang18** [comment]
@shoutOutYangJie
Hi, it seems that you had reproduced the results with 8 V100 GPUs.

1) Did you use the same configurations as in Pretrain.yaml?
2) How many hours per epoch it took for the training?
3) Have you tried to reduce the image resolution from 384 to 224?

Looking forward to your reply.

**Comment by shoutOutYangJie** [comment]
1. Yes
2. about several hours.
3. No.


I can say the work is solid. very good.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "salesforce/ALBEF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月18日(星期六) 晚上11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [salesforce/ALBEF] what size of your A100 gpu's memory? (Issue #31)





 
@shoutOutYangJie
 Hi, it seems that you had reproduced the results with 8 V100 GPUs.
  
Did you use the same configurations as in Pretrain.yaml?
 
How many hours per epoch it took for the training?
 
Have you tried to reduce the image resolution from 384 to 224?
  
Looking forward to your reply.
