### ISSUE TITLE
What is the difference between coco.json and coco_train.json

### ISSUE THREAD

**Issue by shoutOutYangJie** [salesforce/ALBEF#34]
"coco.json" is in the "json_pretrain" dir and has 108MB. 
"coco_train.json" is in the "data" dir and has 84.6MB.

 I am confused about the difference. 
By the way, "data/coco_karpathy_train.json"  points to "coco_train.json" or "coco.json" ?
I want to retrain your model. Thanks.

**Comment by LiJunnan1992** [comment]
Hi, 
"coco.json" and "coco_train.json" contain the same karpathy train split. The difference is that "coco.json" contains absolute images paths where you need to modify, whereas "coco_train.json" contains paths relative to your coco image directory.
