### ISSUE TITLE
The max length of tokenizer is 25?

### ISSUE THREAD

**Issue by shoutOutYangJie** [salesforce/ALBEF#35]
hi, I notice that you set max length of Tokenizer is 25. However, Clip and Align, Filip set 76.  Three times exist. You can't deal with long description, which may leads to bad performance？

**Comment by LiJunnan1992** [comment]
Hi, most of the captions for pre-training have a length shorter than 25, so I set max_length to 25 to save memory cost. The model can still deal with longer text in downstream tasks.
