### ISSUE TITLE
the variance of  loss is very large when initial training.

### ISSUE THREAD

**Issue by shoutOutYangJie** [salesforce/ALBEF#36]
![image](https://user-images.githubusercontent.com/46734514/146323223-4f7f32b0-76fd-4b7d-9e63-0b67e670138d.png)

I want to reproduce your result using your code. I download datasets excluding CC12M.  And I find the three losses vary dramaticly. I don't know whether normal or not?

**Comment by LiJunnan1992** [comment]
The variation you observe between batches should be normal.
