### ISSUE TITLE
selecting pretraining checkpoints / monitoring pretraining performance

### ISSUE THREAD

**Issue by jayleicn** [salesforce/ALBEF#4]
Hi @LiJunnan1992,

A few questions on pretraining: (1) how do you decide which checkpoint to use for each run, are you always using the last checkpoint? (2) and how to compare pretrained checkpoint across runs (3) do you monitor pretraining performance using by using one of the downstream tasks? If so, could you provide some more details?

Best,
Jie

**Comment by LiJunnan1992** [comment]
Hi,

(1) I always use the last checkpoint
(2) I'm not sure what you refer to by runs, because I only pretrain once
(3) no I haven't monitored with downstream tasks during pretraining

**Comment by jayleicn** [comment]
Thanks! For (2) I thought you'd tune the pretraining a bit for best performance.

**Comment by LiJunnan1992** [comment]
To keep things simple, I haven't tuned much on the pretraining hyperparameters,

**Comment by jayleicn** [comment]
Thanks! Then the method becomes even more convincing!!
