### ISSUE TITLE
About VQA answer_list.json

### ISSUE THREAD

**Issue by zengyan-97** [salesforce/ALBEF#40]
Hi, 
Thanks for your nice work! The released code is also very useful. 

I am wondering how did you get answer_list.json. It contains 3,128 answers. However, your paper says that you use 3,192 candidate answers. Meanwhile, in fact existing methods usually use 3,129 answers as reported in their papers. 

I have tried to get top-3,129 most frequent answers on VQA train set or train&validation set. It yields a list that only has ~2700 answers overlapped with your list.

Thanks!

**Comment by LiJunnan1992** [comment]
Hi, thanks for your question!
I used the same 3,129 answers as existing methods, but removed an empty answer candidate that I found, which makes it 3,128 in total. The 3,192 in my paper was a typo, thanks for finding it!

**Comment by zengyan-97** [comment]
Thanks!
