### ISSUE TITLE
vqa training

### ISSUE THREAD

**Issue by Aatrox00** [salesforce/ALBEF#41]
Hi, thanks for sharing. ALBEF is wonderful and your code is well orginized.
What bothers me now is the training process takes too much time. It takes about 10 hours to finetune VQA traning tast per epoch with 3 RTX 3090 GPUs. I'm wondering if there is a way to speed up the training process somehow?
Thanks again for your work.

**Comment by LiJunnan1992** [comment]
Hi, you can try to use ZeRO and other techniques here (https://fairscale.readthedocs.io/en/latest/deep_dive/oss_sdp_fsdp.html) to reduce memory and increase batch size. It would be difficult have a big speed-up if hardware is the limitation.

Thanks!

**Comment by Aatrox00** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Aatrox00** [comment]
I'll try that.
Thanks a lot!
