### ISSUE TITLE
VQA VG answer weight

### ISSUE THREAD

**Issue by jayleicn** [salesforce/ALBEF#42]
Hi Junnan,

I noticed the answers in the VQA dataset are assigned a weight value based on their frequency, and all answers to a question have a total weight of 1. For VG dataset, it looks like the answers are assigned a weight of 0.5 (see https://github.com/salesforce/ALBEF/blob/main/dataset/vqa_dataset.py#L66). Since there is always a single answer to VG questions, if using the same rules as in VQA dataset, the weight should be 1. Do you have any reason not to use a weight value of 1 for VG answers?

Best,
Jie

**Comment by LiJunnan1992** [comment]
Hi Jie,

I set the weight to be smaller than 1 to avoid VG samples to dominate training, due to the domain gap between VG and VQA. I found weight=0.5 gives better performance than weight=1, but haven't tried other values.

**Comment by jayleicn** [comment]
Thanks Junnan! This makes sense!
