### ISSUE TITLE
A quick question about visual grounding and visualizing Grad-CAM

### ISSUE THREAD

**Issue by bellos1203** [salesforce/ALBEF#43]
Thanks for releasing the code!

I have a quick question about visualizing Grad-CAM.
Do you have any particular reason for using 3rd layer of multimodal encoder?
I've tried other layers using your demo code for visualization, but the results generated from the 4th & 5th layers are quite inaccurate.

Thanks in advance :)

**Comment by LiJunnan1992** [comment]
Thanks for your question!
As shown in our appendix (Figure 8), we empirically find that the 3rd cross-attention layer specialize in localization.

**Comment by bellos1203** [comment]
Thanks for your kind reply! 
I missed the appendix.
