### ISSUE TITLE
test in VQA dataset

### ISSUE THREAD

**Issue by haoshuai714** [salesforce/ALBEF#48]
when I test in VQA task, I run :
python -m torch.distributed.launch --nproc_per_node=8 --use_env VQA.py \
--config ./configs/VQA.yaml \
--output_dir output/vqa \
--checkpoint ./ALBEF.pth
But, when I run one epoch, I get the result flood is empty? 
How to get the result? when all epoch training end?

**Comment by LiJunnan1992** [comment]
Yes the result will be generated after all epochs.

**Comment by LiJunnan1992** [comment]
You can also set --evaluate to directly use a finetuned model to generate result.

**Comment by haoshuai714** [comment]
Thanks!

**Comment by haoshuai714** [comment]
Hi: I get the file: vqa_result_epoch7.json. how to get the paper result?

**Comment by LiJunnan1992** [comment]
Please go to the official evaluation server by the VQA team

**Comment by haoshuai714** [comment]
Could you give me a link? Thanks!

**Comment by LiJunnan1992** [comment]
https://eval.ai/web/challenges/challenge-page/830/submission
