### ISSUE TITLE
Training with apex fp16

### ISSUE THREAD

**Issue by kugwzk** [salesforce/ALBEF#5]
Thanks a lot for the interesting work. 
BTW, I see in configs. you always make opt as adamw, did you select apex with fp16 for training or inference? I see in your code only when ope == 'fusedadamw' will use the apex optimizer.

**Comment by LiJunnan1992** [comment]
Hi,
I didn't use fp16. Thanks!

**Comment by kugwzk** [comment]
Thx.

**Comment by haoshuai714** [comment]
> Thx.



> Thanks a lot for the interesting work.
> BTW, I see in configs. you always make opt as adamw, did you select apex with fp16 for training or inference? I see in your code only when ope == 'fusedadamw' will use the apex optimizer.

Have you modified it into the form of fp16?
