### ISSUE TITLE
How to get VQA result?

### ISSUE THREAD

**Issue by haoshuai714** [salesforce/ALBEF#57]
I have get the vqa_result_epoch7.json . How to get VQA result?

**Comment by haoshuai714** [comment]
DEV and STD is submit the same file--vqa_result_epoch7.json?

**Comment by LiJunnan1992** [comment]
> DEV and STD is submit the same file--vqa_result_epoch7.json?

yes

**Comment by haoshuai714** [comment]
Thanks!
