### ISSUE TITLE
grounding results

### ISSUE THREAD

**Issue by ziyanyang** [salesforce/ALBEF#59]
Hi,

I have checked the coco.json file used for pretraining, and I found the images in refcoco+_val.json and refcoco+_test.json files also appear in this pretraining file. Does it mean these images are already "seen" during pretraining step?

**Comment by LiJunnan1992** [comment]
Yes, we have discussed this in Appendix A - Visual Grounding. Thanks!

**Comment by ziyanyang** [comment]
> Yes, we have discussed this in Appendix A - Visual Grounding. Thanks!

Got it. Thanks!
