### ISSUE TITLE
 Question about nlvr checkpoint

### ISSUE THREAD

**Issue by g25h1** [salesforce/ALBEF#67]
I can't find teacher model (_m) in this checkpoint https://storage.googleapis.com/sfr-pcl-data-research/ALBEF/pretrain_model_nlvr.pth. And can you provide the finetuned checkpoint of NLVR2, THANKS~

**Comment by LiJunnan1992** [comment]
Hi, I have removed the teacher model because it is not used during NLVR fine-tuning.

**Comment by g25h1** [comment]
Thanks a lot!

> Hi, I have removed the teacher model because it is not used during NLVR fine-tuning.
