### ISSUE TITLE
Test On Visual Grounding on RefCOCO+ Task

### ISSUE THREAD

**Issue by haoshuai714** [salesforce/ALBEF#69]
1. I have a issue when test On Visual Grounding on RefCOCO+ Task. For example,  I run this command:
python -m torch.distributed.launch --nproc_per_node=8 --use_env Grounding.py --config ./configs/Grounding.yaml --output_dir output/RefCOCO  --gradcam_mode itm --block_num 8 --checkpoint checkpoint_29.pth

2.The program is stuck, as shown below:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 2): env://
| distributed init (rank 6): env://
| distributed init (rank 0): env://
| distributed init (rank 3): env://
| distributed init (rank 4): env://
| distributed init (rank 5): env://
| distributed init (rank 7): env://
| distributed init (rank 1): env://

3. How to test Visual Grounding use the path? could you give me some guide? Thanks!

**Comment by LiJunnan1992** [comment]
Hi, I'm not sure why your program is stuck, maybe you want to check if you can run pytorch distributed training with other scripts.

**Comment by haoshuai714** [comment]
The run command is correct?

**Comment by haoshuai714** [comment]
Grounding. Yaml file. What is "refcoco_data: 'data' " stored in the file?

**Comment by waterpeople** [comment]
hi，i am encounter the same problem。could you tell me how can i solve the problem？
