### ISSUE TITLE
Got key error when loading weights finetuning on MSCOCO-retrieval

### ISSUE THREAD

**Issue by wqtwjt1996** [salesforce/ALBEF#7]
Traceback (most recent call last):
  File "Retrieval.py", line 397, in <module>
    main(args, config)
  File "Retrieval.py", line 265, in main
    state_dict = checkpoint['model']
KeyError: 'model'

**Comment by LiJunnan1992** [comment]
It seems that the pre-trained checkpoint is not loaded properly. Can I know what command did you use to fine-tune?

**Comment by wqtwjt1996** [comment]
python -m torch.distributed.launch --nproc_per_node=8 --use_env Retrieval.py \
--config ./configs/Retrieval_flickr.yaml \
--output_dir output/Retrieval_flickr \
--checkpoint [Pretrained checkpoint]

checkpoint is from MSCOCO-retreval

**Comment by LiJunnan1992** [comment]
The released MSCOCO-retrieval checkpoint does not contain parameters for the momentum encoder. You can set distill=False in the config file to avoid this error.
