### ISSUE TITLE
Question about initialising Bert while pretraining

### ISSUE THREAD

**Issue by MiraclesinWang** [salesforce/ALBEF#76]
Hello, ALBEF is really an amazing VLP model. Thanks for your contribution. 
Nevertheless, I have encountered a problem when using it. Would you do me a favor?

I know you **rewrite** _transformers.models.bert.modeling_bert_ and put it in _xbert.py_.
After checking your file, I found some parameters were renamed when rewriting the last 6 layers of Bert. For example, your model has a parameter named '_bert.encoder.layer.10.crossattention.self.value.weight_', while the counterpart in the model defined in _transformers.models.bert.modeling_bert_ is '_bert.encoder.layer.10.attention.self.value.weight_'. However, you initialise Bert with the function '_from_pretrained_' defined in _transformers.modeling_utils.PreTrainedModel_. 

To the best of my knowledge, the '_from_pretrained_' function just mentioned will download parameters from web hub if no path is given, which can happen when you set the first arg to 'bert-base-uncased'. However, the parameters downloaded are entitled in the same way as that in _transformers.models.bert.modeling_bert_, whose parameters' names are slightly different from yours. 
Consequently, some parameters in your model, like the '_bert.encoder.layer.10.crossattention.self.value.weight_' I've just mentioned, can't be initialised properly. 

I don't find any code which deals with this problem. 
Is this a bug? Or is there some way you deal with this problem which I neglect? Or is it an unimportant itch since you will pretrain it afterwards?

**Comment by MiraclesinWang** [comment]
To demonstrate my question, I use pdb to check the running process in '_from_pretrained_' function of _transformers.modeling_utils.PreTrainedModel_. And this is a screenshot. As you can see, some of your model's parameters are among the '**missing keys**', which means they are not initialised properly. 
![QQ截图20220428162553](https://user-images.githubusercontent.com/61409495/165710895-55114f98-edff-4a44-89a3-4485826d3353.png)

**Comment by LiJunnan1992** [comment]
We add the cross attention layers as additional parameters. They are randomly initialised and pre-trained by ALBEF.

**Comment by MiraclesinWang** [comment]
Thanks for your answer.
