### ISSUE TITLE
Pre-training on custom datasets

### ISSUE THREAD

**Issue by ZhiweiXie1** [salesforce/ALBEF#77]
Hello, I'm a deep learning beginner.

If the dataset is small, can I train my own dataset?  I tried my own dataset and got the following error. 

header, total_time_str, total_time / len(iterable)))
ZeroDivisionError: float division by zero

**Comment by LiJunnan1992** [comment]
That means your dataset is too small to fit in a batch. You can reduce the batch size.

**Comment by ZhiweiXie1** [comment]
Thanks
