### ISSUE TITLE
meta info about the pre-trained checkpoint

### ISSUE THREAD

**Issue by snakeztc** [salesforce/ALBEF#9]
Is the released pre-trained checkpoint trained on the 4M or 14M full dataset?
<img width="784" alt="Screen Shot 2021-08-29 at 12 26 33 AM" src="https://user-images.githubusercontent.com/1688939/131224405-8f96c39a-1b26-439d-a80c-b328834ac27f.png">

**Comment by LiJunnan1992** [comment]
It is trained on 14M dataset.

**Comment by snakeztc** [comment]
Thanks!
