### ISSUE TITLE
Question about VQA answer tokenizer

### ISSUE THREAD

**Issue by katrina433** [salesforce/ALBEF#91]
I realized that an eos token `[SEP]` is added to each answer when creating the VQA dataset [here](https://github.com/salesforce/ALBEF/blob/main/dataset/vqa_dataset.py#L68). Since `BertTokenizer` already appends a `[SEP]` token to the end of each input text anyways, is there a reason why an additional eos token is added to each answer? (the tokenized input_ids of each answer ends with two `102`s (the `sep_token_id`)).

**Comment by LiJunnan1992** [comment]
Hi, we have customized BertTokenizer to not automatically add [SEP] after text.
https://github.com/salesforce/ALBEF/blob/main/models/tokenization_bert.py

**Comment by katrina433** [comment]
I see, thanks for the clarification!
