### ISSUE TITLE
ALBEF VQA test_dev results failed in VQA official server

### ISSUE THREAD

**Issue by sanyalsunny111** [salesforce/ALBEF#96]
I tried using the ALBEF VQA finetuned model along with the the vqa_test_dev.json (provided for downstream tasks) and ran evaluation on it. But when I uploaded the result.json file to the official server it failed (multiple times). Screenshot and error report attached as screenshots. Any feedback?
![image](https://user-images.githubusercontent.com/36811567/183772760-c4de7728-41cc-4039-b12b-12ad593a6109.png)

![image](https://user-images.githubusercontent.com/36811567/183772945-5ff754d9-0ecf-4753-adf4-3c13a194221a.png)

**Comment by LiJunnan1992** [comment]
Hi, as written in the message. The VQA evaluation server has been updated and now needs ALL test questions even for evaluating on test-dev.
